{
 "title": "Luft",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Luft", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\" or r[\"_measurement\"] == \"TEMP\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BME\" or  r[\"_field\"] == \"TYPK\" or r[\"_field\"] == \"TYP_K\" or r[\"_field\"] == \"SHT\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"HUM\" or r[\"_measurement\"] == \"humidity\" or r[\"_measurement\"] == \"RelativeHumidity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BME\" or r[\"_field\"] == \"SHT\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "AmbientPressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PRES\" or r[\"_measurement\"] == \"pressure\" or r[\"_measurement\"] == \"AmbientPressure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BME\")\r\n  |> filter(fn: (r) => r[\"einheit\"] == \"hPa\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "AmbientPressure (pascal)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PRES\" or r[\"_measurement\"] == \"pressure\" or r[\"_measurement\"] == \"AmbientPressure\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"BME\")\r\n  |> filter(fn: (r) => r[\"einheit\"] == \"\\\\pascal\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CO2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MHZ\" or r[\"_field\"] == \"CCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "TVOC (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TVOC\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Staub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Concentration (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CONCENTRATION\" or r[\"_measurement\"] == \"Concentration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DUST\" or r[\"_field\"] == \"Dust\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Mic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Max Ambient noise level (DB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MAX\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Ambient noise level (DB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"VAL\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Licht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Blue Light (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"BLUE\" or r[\"_measurement\"] == \"Blue\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Red Light (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RED\" or r[\"_measurement\"] == \"Red\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Green Light (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"GREEN\" or r[\"_measurement\"] == \"Green\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Clear Light (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CLEARCOL\" or r[\"_measurement\"] == \"ClearCol\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lux (lx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LUX\" or r[\"_measurement\"] == \"Lux\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Colortemperature (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"COLORTEMP\" or r[\"_measurement\"] == \"ColorTemperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TCS\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "UV (counts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"UV\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"UV\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "RATIO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RATIO\" or r[\"_measurement\"] == \"Ratio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DUST\" or r[\"_field\"] == \"Dust\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "LOWPULSEOCCUPANCY",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LOWPULSEOCCUPANCY\" or r[\"_measurement\"] == \"LowPulseOccupancy\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"DUST\" or  r[\"_field\"] == \"Dust\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Microvolt Typ K ADC (uV)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "query": "from(bucket: \"luftqualitaet\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ADC\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TYPK_ADC\" or r[\"_field\"] == \"TYP_K\")\r\n  |> drop(columns: [\"_measurement\"])\r\n  |> drop(columns: [\"einheit\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}